
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb

  pasteforge:
  # todo env file
    image: pasteforge:latest
    # build:
    #   context: .
    #   dockerfile: Dockerfile
    env_file: .env
    ports:
      - "8080:8080"

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"