services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 134217728 # 128*2^20 bytes = 128Mb

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  pasteforge:
    image: shravanasati/pasteforge:latest
    depends_on:
      postgres:
          condition: service_healthy
    env_file: .env
    environment:
      - GIN_MODE=release
      - DIST_DIR="./dist"
      - PORT=8080
      - POSTGRES_HOSTNAME=postgres
    ports:
      - "8080:8080"

  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"