CREATE TABLE pastes (
	id VARCHAR(8) PRIMARY KEY,
	content TEXT NOT NULL,
	created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
	expires_at TIMESTAMPTZ DEFAULT 'infinity',
	visibility VARCHAR(10) NOT NULL DEFAULT 'public',
	language  VARCHAR(20) NOT NULL,
	password VARCHAR
);

CREATE TABLE users (
	username VARCHAR PRIMARY KEY,
	email VARCHAR
);