// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package crud

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Paste struct {
	ID         string
	Content    string
	CreatedAt  pgtype.Timestamptz
	ExpiresAt  pgtype.Timestamptz
	Visibility string
	Language   string
	Password   pgtype.Text
}

type User struct {
	Username string
	Email    pgtype.Text
}
