// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: query.sql

package crud

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaste = `-- name: CreatePaste :exec
INSERT INTO
   pastes ( id, content, expires_at, visibility, language, password ) 
VALUES
   (
      $1, $2, $3, $4, $5, $6
   )
`

type CreatePasteParams struct {
	ID         string
	Content    string
	ExpiresAt  pgtype.Timestamp
	Visibility string
	Language   string
	Password   pgtype.Text
}

func (q *Queries) CreatePaste(ctx context.Context, arg CreatePasteParams) error {
	_, err := q.db.Exec(ctx, createPaste,
		arg.ID,
		arg.Content,
		arg.ExpiresAt,
		arg.Visibility,
		arg.Language,
		arg.Password,
	)
	return err
}

const getPaste = `-- name: GetPaste :one
SELECT id, content, created_at, expires_at, visibility, language, password FROM pastes
WHERE id=$1
`

func (q *Queries) GetPaste(ctx context.Context, id string) (Paste, error) {
	row := q.db.QueryRow(ctx, getPaste, id)
	var i Paste
	err := row.Scan(
		&i.ID,
		&i.Content,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.Visibility,
		&i.Language,
		&i.Password,
	)
	return i, err
}
